name: Simple Snake
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jasonlong/isometric-contributions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
